name: Harshit Kumar
email: kumar_harshit@outlook.com
description: Technical Fridays - personal website and blog
url: https://kHarshit.github.io
github_username: kHarshit
twitter_username: harshit_kumar1
kaggle_username: k2harshit
linkedin_username: kHarshit
stackoverflow_username: 6210807/kHarshit

# use master  branch for jekyll-github-metadata
github:
  source:
    branch: master


# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title


# Google services
google_analytics: UA-103268503-1

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"


plugins:
  - jekyll-feed
  - jekyll-sitemap  # sitemap at /sitemap.xml
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-github-metadata